inherits = "tokyonight_day"

"type" = { fg = "yellow" }
"constant" = { fg = "orange" }
"constant.builtin" = { fg = "red", modifiers = ["italic"] }
"constant.builtin.boolean" = { fg = "orange" }
"constant.character.escape" = { fg = "fg2" }
"constant.numeric" = { fg = "orange" }
"string" = { fg = "green" }
"string.regexp" = { fg = "yellow" }
"string.special" = { fg = "yellow" }
"comment" = { fg = "comment", modifiers = ["italic"] }
"variable" = { fg = "black" }
"variable.builtin" = { fg = "red", modifiers = ["italic"] }
"variable.parameter" = { fg = "magenta-dim", modifiers = ["italic"] }
"variable.other.member" = { fg = "blue" }
"label" = { fg = "yellow" }
"punctuation" = { fg = "fg2" }
"punctuation.delimiter" = { fg = "fg2" }
"punctuation.bracket" = { fg = "fg2" }
"punctuation.special" = { fg = "cyan" }
"keyword" = { fg = "magenta" }
"keyword.control" = { fg = "magenta" }
"keyword.control.import" = { fg = "magenta" }
"keyword.directive" = { fg = "pink" }
"keyword.operator" = { fg = "fg2" }
"keyword.storage" = { fg = "magenta" }
"operator" = { fg = "fg2" }
"function" = { fg = "blue-dim", modifiers = ["italic"] }
"function.builtin" = { fg = "cyan-dim" }
"function.macro" = { fg = "pink" }
"tag" = { fg = "red" }
"namespace" = { fg = "yellow", modifiers = ["italic"] }
"attribute" = { fg = "magenta-dim", modifiers = ["italic"] }
"constructor" = { fg = "blue-dim" }
"module" = { fg = "yellow" }
"special" = { fg = "cyan" }

"markup.heading" = { fg = "magenta", modifiers = ["bold"] }
"markup.raw.inline" = { fg = "green" }
"markup.raw.block" = { fg = "cyan" }
"markup.bold" = { fg = "orange", modifiers = ["bold"] }
"markup.italic" = { fg = "magenta-dim", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.list" = { fg = "red" }
"markup.quote" = { fg = "comment" }
"markup.link.url" = { fg = "blue", underline = { style = "line" } }
"markup.link.text" = { fg = "cyan" }

"diff.plus" = { fg = "green" }
"diff.delta" = { fg = "blue" }
"diff.minus" = { fg = "red" }

"diagnostic.hint".underline = { color = "green", style = "curl" }
"diagnostic.info".underline = { color = "blue", style = "curl" }
"diagnostic.warning".underline = { color = "yellow", style = "curl" }
"diagnostic.error".underline = { color = "red", style = "curl" }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

"hint" = { fg = "green", modifiers = ["bold"] }
"info" = { fg = "blue", modifiers = ["bold"] }
"warning" = { fg = "yellow", modifiers = ["bold"] }
"error" = { fg = "red", modifiers = ["bold"] }

"ui.background" = { bg = "bg" }
"ui.background.separator" = { fg = "bg4" }
"ui.virtual" = { fg = "bg4" }
"ui.virtual.indent-guide" = { fg = "bg4" }
"ui.virtual.whitespace" = { fg = "bg4" }
"ui.virtual.ruler" = { bg = "bg2" }
"ui.virtual.inlay-hint" = { fg = "fg3", bg = "bg0" }
"ui.virtual.jump-label" = { fg = "red", modifiers = ["bold"] }

"ui.cursor" = { fg = "bg", bg = "fg" }
"ui.cursor.primary" = { fg = "bg", bg = "fg" }
"ui.cursor.insert" = { fg = "bg", bg = "cyan" }
"ui.cursor.select" = { fg = "bg", bg = "blue" }
"ui.cursor.match" = { bg = "sel1", modifiers = ["bold"] }

"ui.selection" = { bg = "sel0" }
"ui.selection.primary" = { bg = "sel1" }
"ui.cursorline.primary" = { bg = "bg3" }
"ui.cursorline.secondary" = { bg = "bg2" }

"ui.highlight" = { bg = "bg2" }
"ui.highlight.frameline" = { bg = "change" }

"ui.linenr" = { fg = "fg3" }
"ui.linenr.selected" = { fg = "yellow", modifiers = ["bold"] }

"ui.statusline" = { fg = "fg2", bg = "bg0" }
"ui.statusline.inactive" = { fg = "comment", bg = "bg0" }
"ui.statusline.normal" = { fg = "bg", bg = "blue", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "bg", bg = "green", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "bg", bg = "magenta", modifiers = ["bold"] }

"ui.bufferline" = { fg = "fg3", bg = "bg0" }
"ui.bufferline.active" = { fg = "fg", bg = "sel0", modifiers = ["bold"] }
"ui.bufferline.background" = { bg = "bg0" }

"ui.text" = { fg = "fg" }
"ui.text.directory" = { fg = "blue" }
"ui.text.focus" = { fg = "fg", modifiers = ["bold"] }

"ui.help" = { fg = "fg", bg = "bg2" }
"ui.popup" = { fg = "fg", bg = "bg0" }
"ui.window" = { fg = "bg4" }
"ui.menu" = { fg = "fg", bg = "bg0" }
"ui.menu.selected" = { fg = "fg", bg = "sel1" }
"ui.menu.scroll" = { fg = "fg", bg = "bg2" }

"ui.debug" = { fg = "red" }

[palette]
bg = "#F6F2EE"
bg0 = "#E4DCD4"
bg2 = "#DBD1DD"
bg3 = "#D3C7BB"
bg4 = "#AAB0AD"
fg = "#3D2B5A"
fg2 = "#643F61"
fg3 = "#824D5B"
comment = "#837A72"
black = "#352C24"
red = "#A5222F"
green = "#396847"
yellow = "#AC5402"
blue = "#2848A9"
blue-dim = "#223D90"
magenta = "#6E33CE"
magenta-dim = "#8B369A"
cyan = "#287980"
cyan-dim = "#488D93"
orange = "#AC5402"
pink = "#A440B5"
sel0 = "#E7D2BE"
sel1 = "#A4C1C2"
change = "#CDD0E0"
